### ISSUE TITLE
16.08 - notes

### ISSUE THREAD

**Issue by sv-khol** [AlyonaShchukina/pretzel-new#2]
1. <title>Главная</title>
Сколько "главных" закладок может быть открыто в браузере? Если все будут просто "главными" - запутаешься напрочь... Поэтому лучше уточнять: "Брецель. Главная" - тогда пользователь сразу по первым буквам уже быдет видеть, что за сайт открыт на вкалдке

2. section class="second_block"
там нет необходимости приделывать div class="container" 2 раза. Достаточно одного, и у него внутри два флекса.

3. у img class="sb_img1" src="photo/pretzel1.JPG" 
.sb_img1 {
    display: flex; - это ни к чему - у имаджа нет детей, которые бы этому флексу подчинились....
...
}
у .sb_text, .sb_text2 то же самое: флекс - лишний!

4. у картинок с описанием классов можно было поступить как с текстами - там все свойства повторяются, кроме высоты

5. хотелось бы и полную адаптивность получить за счет флекса ;) Чтобы на мал экранах картинки и текст вставали друг ПОД другом, а не рядом.

**Comment by AlyonaShchukina** [comment]
Уточните, пожалуйста, по поводу второго пункта. Не совсем поняла о чем речь.

**Comment by sv-khol** [comment]
исправила коммент. Забыла, что язык разметки теги не отображает в тексте - они и исчезли, пытаясь отрислваться имено как теги ))))
